name: climasense
description: App per l'ottimizzazione della curva climatica.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- CORE ---
  cupertino_icons: ^1.0.2

  # --- DATABASE & STORAGE ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  file_picker: ^8.1.4     # Per selezionare file (Restore)
  share_plus: ^10.0.0    # Per "Salva dove vuoi" (Backup/Export)

  # --- UI & GRAFICI ---
  fl_chart: ^0.66.0
  intl: ^0.19.0

  # --- EXPORT & FILES ---
  pdf: ^3.10.4
  printing: ^5.11.0

  # --- METEO AUTOMATICO ---
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  http: ^1.2.0

  # --- NOTIFICHE ---
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  # RIMOSSO: flutter_timezone (causa errori di compilazione con Android v2)

  # --- PERMESSI ---
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # --- CODE GENERATION ---
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
